---
mysql:
  nameOverride: laravel-database
  auth:
    database: laravel
    rootPassword: example

memcached:
  nameOverride: laravel-cache

laravel-nginx:
  image:
    php:
      repository: isieiam/laravel
      tag: "1.0"
    nginx:
      repository: nginx
      tag: "stable-alpine"

  database:
    Connection: mysql
    Host: laravel-database
    Port: 3306
    passwordkey: "mysql-root-password"
    Name: "laravel"

  cache:
    cachedriver: "memcached"
    sessiondriver: "memcached"
    host: "laravel-cache"

  port:
    nginx: 80
    php: 9000

  ingress:
    class: nginx
    host: laravel.localhost
    #host: 84.252.129.137.nip.io

  service:
    internalPort: 80
    externalPort: 8080

laravel-nginx-exporter:
  host: "laravel-nginx"
  port: "8080"

flux:
  git:
    url: https://github.com/IsieIam/laravel_deploy.git
    branch: grafana-flux
    readonly: true
    path: dashboards
    pollInterval: 1m
  registry:
    automationInterval: 1m