version: '3.3'
services:
  laravel:
    # image: ${DH_USERNAME}/laravel:${LARAVEL_VERSION}
    build:
      context: ./laravel/
    ports:
      - ${LARAVEL_PORT}:${LARAVEL_PORT}/tcp
    volumes: 
    #  - ../laravel:/var/www/html:cached
      - ./lara.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.env_lara:/var/www/html/.env
    #environment:
    #  - MONGO=se_ui_db
    networks:
      - front_net

  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}/tcp
    volumes:
      - ../laravel:/var/www/html:cached
      - ./nginx/lara.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front_net

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.0.1.0/24"